[phases.setup]
nixPkgs = ["nodejs_20"]
nixpkgsUrl = "https://github.com/NixOS/nixpkgs/archive/nixos-23.11.tar.gz"
nixOverlays = ["https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz"]
[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npx vite build",
  "npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist --minify"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"