[phases.setup]
# Utilise uniquement le paquet "nodejs_20".
# npm est inclus par défaut avec ce paquet et n'a pas besoin d'être spécifié.
nixPkgs = ["nodejs_20"]

# L'overlay de Railway n'est pas nécessaire et a probablement causé la première erreur.
# Il est plus sûr de le retirer pour utiliser un environnement Nix standard.
# nixOverlays = ["https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz"]

# Il est bon de laisser cette ligne pour garantir une version stable.
nixpkgsUrl = "https://github.com/NixOS/nixpkgs/archive/nixos-23.11.tar.gz"

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npx vite build",
  "npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist --minify"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"